-- vim.cmd('colorscheme aurora')
require "user.options"
require "user.plugins"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter" --ts-rainbow settings in tresitter config file
require "user.treesitter-playground"
require "user.autopairs"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.colorizer"
require "user.autocommands"
require "user.toggle"
require "user.modes"
require "user.beacon"
require "user.colorscheme"
require "user.keybindings"

