require("nvim-web-devicons").set_icon {
 [".babelrc"] = {
    icon = "ﬥ",
    color = "#45f3d3",
    cterm_color = "185",
    name = "Babelrc",
  },
  [".bash_profile"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "113",
    name = "BashProfile",
  },
  [".bashrc"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "113",
    name = "Bashrc",
  },
  [".DS_Store"] = {
    icon = "",
    color = "#bc95ff",
    cterm_color = "59",
    name = "DsStore",
  },
  [".gitattributes"] = {
    icon = "",
    color = "#bc95ff",
    cterm_color = "59",
    name = "GitAttributes",
  },
  [".gitconfig"] = {
    icon = "",
    color = "#bc95ff",
    cterm_color = "59",
    name = "GitConfig",
  },
  [".gitignore"] = {
    icon = "",
    color = "#bc95ff",
    cterm_color = "59",
    name = "GitIgnore",
  },
  [".gitlab-ci.yml"] = {
    icon = "",
    color = "#ff8d01",
    cterm_color = "166",
    name = "GitlabCI",
  },
  [".gitmodules"] = {
    icon = "",
    color = "#bc95ff",
    cterm_color = "59",
    name = "GitModules",
  },
  [".gvimrc"] = {
    icon = "",
    color = "#46a07b",
    cterm_color = "29",
    name = "Gvimrc",
  },
  [".npmignore"] = {
    icon = "",
    color = "#14ffa9",
    cterm_color = "161",
    name = "NPMIgnore",
  },
  [".npmrc"] = {
    icon = "",
    color = "#14ffa9",
    cterm_color = "161",
    name = "NPMrc",
  },
  [".settings.json"] = {
    icon = "",
    color = "#854CC7",
    cterm_color = "98",
    name = "SettingsJson",
  },
  [".vimrc"] = {
    icon = "",
    color = "#46a07b",
    cterm_color = "29",
    name = "Vimrc",
  },
  [".zprofile"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "113",
    name = "Zshprofile",
  },
  [".zshenv"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "113",
    name = "Zshenv",
  },
  [".zshrc"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "113",
    name = "Zshrc",
  },
  ["Brewfile"] = {
    icon = "",
    color = "#cd1bfd",
    cterm_color = "52",
    name = "Brewfile",
  },
  ["CMakeLists.txt"] = {
    icon = "",
    color = "#89c9ec",
    cterm_color = "66",
    name = "CMakeLists",
  },
  ["COMMIT_EDITMSG"] = {
    icon = "",
    color = "#bc95ff",
    cterm_color = "59",
    name = "GitCommit",
  },
  ["COPYING"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "185",
    name = "License",
  },
  ["COPYING.LESSER"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "185",
    name = "License",
  },
  ["Dockerfile"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "59",
    name = "Dockerfile",
  },
  ["Gemfile$"] = {
    icon = "",
    color = "#cd1bfd",
    cterm_color = "52",
    name = "Gemfile",
  },
  ["LICENSE"] = {
    icon = "",
    color = "#b6aef4",
    cterm_color = "179",
    name = "License",
  },
  ["R"] = {
    icon = "ﳒ",
    color = "#ffad49",
    cterm_color = "65",
    name = "R",
  },
  ["Rmd"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Rmd",
  },
  ["Vagrantfile$"] = {
    icon = "",
    color = "#1563FF",
    cterm_color = "27",
    name = "Vagrantfile",
  },
  ["_gvimrc"] = {
    icon = "",
    color = "#46a07b",
    cterm_color = "29",
    name = "Gvimrc",
  },
  ["_vimrc"] = {
    icon = "",
    color = "#46a07b",
    cterm_color = "29",
    name = "Vimrc",
  },
  ["ai"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "185",
    name = "Ai",
  },
  ["awk"] = {
    icon = "",
    color = "#b6aef4",
    cterm_color = "59",
    name = "Awk",
  },
  ["bash"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "113",
    name = "Bash",
  },
  ["bat"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "154",
    name = "Bat",
  },
  ["bmp"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Bmp",
  },
  ["c"] = {
    icon = "",
    color = "#599eff",
    cterm_color = "75",
    name = "C",
  },
  ["c++"] = {
    icon = "",
    color = "#ff8d01",
    cterm_color = "204",
    name = "CPlusPlus",
  },
  ["cbl"] = {
    icon = "⚙",
    color = "#7700df",
    cterm_color = "25",
    name = "Cobol",
  },
  ["cc"] = {
    icon = "",
    color = "#ff8d01",
    cterm_color = "204",
    name = "CPlusPlus",
  },
  ["cfg"] = {
    icon = "",
    color = "#72e9f4",
    cterm_color = "231",
    name = "Configuration",
  },
  ["clj"] = {
    icon = "",
    color = "#72e9f4",
    cterm_color = "107",
    name = "Clojure",
  },
  ["cljc"] = {
    icon = "",
    color = "#72e9f4",
    cterm_color = "107",
    name = "ClojureC",
  },
  ["cljs"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "ClojureJS",
  },
  ["cljd"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "ClojureDart",
  },
  ["cmake"] = {
    icon = "",
    color = "#89c9ec",
    cterm_color = "66",
    name = "CMake",
  },
  ["cob"] = {
    icon = "⚙",
    color = "#7700df",
    cterm_color = "25",
    name = "Cobol",
  },
  ["cobol"] = {
    icon = "⚙",
    color = "#7700df",
    cterm_color = "25",
    name = "Cobol",
  },
  ["coffee"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "185",
    name = "Coffee",
  },
  ["conf"] = {
    icon = "",
    color = "#89c9ec",
    cterm_color = "66",
    name = "Conf",
  },
  ["config.ru"] = {
    icon = "",
    color = "#cd1bfd",
    cterm_color = "52",
    name = "ConfigRu",
  },
  ["cp"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Cp",
  },
  ["cpp"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Cpp",
  },
  ["cpy"] = {
    icon = "⚙",
    color = "#7700df",
    cterm_color = "25",
    name = "Cobol",
  },
  ["cr"] = {
    icon = "",
    color = "#bc95ff",
    cterm_color = "16",
    name = "Crystal",
  },
  ["cs"] = {
    icon = "",
    color = "#89c9ec",
    cterm_color = "58",
    name = "Cs",
  },
  ["csh"] = {
    icon = "",
    color = "#b6aef4",
    cterm_color = "59",
    name = "Csh",
  },
  ["cson"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "185",
    name = "Cson",
  },
  ["css"] = {
    icon = "",
    color = "#42a5f5",
    cterm_color = "39",
    name = "Css",
  },
  ["csv"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "113",
    name = "Csv",
  },
  ["cxx"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Cxx",
  },
  ["d"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "64",
    name = "D",
  },
  ["dart"] = {
    icon = "",
    color = "#03589C",
    cterm_color = "25",
    name = "Dart",
  },
  ["db"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "188",
    name = "Db",
  },
  ["desktop"] = {
    icon = "",
    color = "#ff02c4",
    cterm_color = "60",
    name = "DesktopEntry",
  },
  ["diff"] = {
    icon = "",
    color = "#bc95ff",
    cterm_color = "59",
    name = "Diff",
  },
  ["doc"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "25",
    name = "Doc",
  },
  ["dockerfile"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "59",
    name = "Dockerfile",
  },
  ["drl"] = {
    icon = "",
    color = "#b6aef4",
    cterm_color = "217",
    name = "Drools",
  },
  ["dropbox"] = {
    icon = "",
    color = "#0061FE",
    cterm_color = "27",
    name = "Dropbox",
  },
  ["dump"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "188",
    name = "Dump",
  },
  ["edn"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Edn",
  },
  ["eex"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Eex",
  },
  ["ejs"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "185",
    name = "Ejs",
  },
  ["elm"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Elm",
  },
  ["epp"] = {
    icon = "",
    color = "#45f3d3",
    name = "Epp",
  },
  ["erb"] = {
    icon = "",
    color = "#cd1bfd",
    cterm_color = "52",
    name = "Erb",
  },
  ["erl"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "132",
    name = "Erl",
  },
  ["ex"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Ex",
  },
  ["exs"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Exs",
  },
  ["f#"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Fsharp",
  },
  ["favicon.ico"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "185",
    name = "Favicon",
  },
  ["fnl"] = {
    color = "#46a07b",
    icon = "🌜",
    cterm_color = "230",
    name = "Fennel"
  },
  ["fish"] = {
    icon = "",
    color = "#b6aef4",
    cterm_color = "59",
    name = "Fish",
  },
  ["fs"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Fs",
  },
  ["fsi"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Fsi",
  },
  ["fsscript"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Fsscript",
  },
  ["fsx"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Fsx",
  },
  ["gd"] = {
    icon = "",
    color = "#89c9ec",
    cterm_color = "66",
    name = "GDScript",
  },
  ["gemspec"] = {
    icon = "",
    color = "#cd1bfd",
    cterm_color = "52",
    name = "Gemspec",
  },
  ["gif"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Gif",
  },
  ["git"] = {
    icon = "",
    color = "#9d00ff",
    cterm_color = "202",
    name = "GitLogo",
  },
  ["glb"] = {
    icon = "",
    color = "#ffad49",
    cterm_color = "215",
    name = "BinaryGLTF",
  },
  ["go"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Go",
  },
  ["godot"] = {
    icon = "",
    color = "#89c9ec",
    cterm_color = "66",
    name = "GodotProject",
  },
  ["gruntfile"] = {
    icon = "",
    color = "#ffad49",
    cterm_color = "173",
    name = "Gruntfile",
  },
  ["gulpfile"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "167",
    name = "Gulpfile",
  },
  ["h"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "H",
  },
  ["haml"] = {
    icon = "",
    color = "#cd1bfd",
    cterm_color = "188",
    name = "Haml",
  },
  ["hbs"] = {
    icon = "",
    color = "#f0772b",
    cterm_color = "208",
    name = "Hbs",
  },
  ["heex"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Heex",
  },
  ["hh"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Hh",
  },
  ["hpp"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Hpp",
  },
  ["hrl"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "132",
    name = "Hrl",
  },
  ["hs"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Hs",
  },
  ["htm"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "166",
    name = "Htm",
  },
  ["html"] = {
    icon = "",
    color = "#46a07b",
    cterm_color = "202",
    name = "Html",
  },
  ["hxx"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Hxx",
  },
  ["ico"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "185",
    name = "Ico",
  },
  ["import"] = {
    icon = "",
    color = "#72e9f4",
    cterm_color = "231",
    name = "ImportConfiguration",
  },
  ["ini"] = {
    icon = "",
    color = "#89c9ec",
    cterm_color = "66",
    name = "Ini",
  },
  ["java"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "167",
    name = "Java",
  },
  ["jl"] = {
    icon = "",
    color = "#a270ba",
    cterm_color = "133",
    name = "Jl",
  },
  ["jpeg"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Jpeg",
  },
  ["jpg"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Jpg",
  },
  ["js"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "185",
    name = "Js",
  },
  ["json"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "185",
    name = "Json",
  },
  ["jsx"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Jsx",
  },
  ["ksh"] = {
    icon = "",
    color = "#b6aef4",
    cterm_color = "59",
    name = "Ksh",
  },
  ["kt"] = {
    icon = "𝙆",
    color = "#ff8d01",
    cterm_color = "208",
    name = "Kotlin",
  },
  ["kts"] = {
    icon = "𝙆",
    color = "#ff8d01",
    cterm_color = "208",
    name = "KotlinScript",
  },
  ["leex"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Leex",
  },
  ["less"] = {
    icon = "",
    color = "#ff02c4",
    cterm_color = "60",
    name = "Less",
  },
  ["lhs"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Lhs",
  },
  ["license"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "185",
    name = "License",
  },
  ["lua"] = {
    icon = "",
    color = "#51a0cf",
    cterm_color = "74",
    name = "Lua",
  },
  ["makefile"] = {
    icon = "",
    color = "#89c9ec",
    cterm_color = "66",
    name = "Makefile",
  },
  ["markdown"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Markdown",
  },
  ["material"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "132",
    name = "Material",
  },
  ["md"] = {
    icon = "",
    color = "#ffffff",
    cterm_color = "white",
    name = "Md",
  },
  ["mdx"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Mdx",
  },
  ["mint"] = {
    icon = "",
    color = "#87c095",
    cterm_color = "108",
    name = "Mint",
  },
  ["mix.lock"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "MixLock",
  },
  ["mjs"] = {
    icon = "",
    color = "#14ffa9",
    cterm_color = "221",
    name = "Mjs",
  },
  ["ml"] = {
    icon = "λ",
    color = "#ffad49",
    cterm_color = "173",
    name = "Ml",
  },
  ["mli"] = {
    icon = "λ",
    color = "#ffad49",
    cterm_color = "173",
    name = "Mli",
  },
  ["mo"] = {
    icon = "∞",
    color = "#9772FB",
    cterm_color = "99",
    name = "Motoko",
  },
  ["mustache"] = {
    icon = "",
    color = "#ffad49",
    cterm_color = "173",
    name = "Mustache",
  },
  ["nim"] = {
    icon = "👑",
    color = "#ff02c4",
    cterm_color = "220",
    name = "Nim",
  },
  ["nix"] = {
    icon = "",
    color = "#7ebae4",
    cterm_color = "110",
    name = "Nix",
  },
  ["node_modules"] = {
    icon = "",
    color = "#14ffa9",
    cterm_color = "161",
    name = "NodeModules",
  },
  ["opus"] = {
    icon = "",
    color = "#ff8d01",
    cterm_color = "208",
    name = "OPUS",
  },
  ["otf"] = {
    icon = "",
    color = "#72e9f4",
    cterm_color = "231",
    name = "OpenTypeFont",
  },
  ['package.json'] = {
    icon = "",
    color = "#14ffa9",
    name = "PackageJson"
  },
  ['package-lock.json'] = {
    icon = "",
    color = "#d5bdff",
    name = "PackageLockJson"
  },
  ["pck"] = {
    icon = "",
    color = "#89c9ec",
    cterm_color = "66",
    name = "PackedResource",
  },
  ["pdf"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "124",
    name = "Pdf",
  },
  ["php"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Php",
  },
  ["pl"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Pl",
  },
  ["pm"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Pm",
  },
  ["png"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Png",
  },
  ["pp"] = {
    icon = "",
    color = "#45f3d3",
    name = "Pp",
  },
  ["ppt"] = {
    icon = "",
    color = "#03c0fa",
    cterm_color = "167",
    name = "Ppt",
  },
  ["pro"] = {
    icon = "",
    color = "#e4b854",
    cterm_color = "179",
    name = "Prolog",
  },
  ["Procfile"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Procfile",
  },
  ["ps1"] = {
    icon = "",
    color = "#b6aef4",
    cterm_color = "59",
    name = "PromptPs1",
  },
  ["psb"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Psb",
  },
  ["psd"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Psd",
  },
  ["py"] = {
    icon = "",
    color = "#ffad49",
    cterm_color = "61",
    name = "Py",
  },
  ["pyc"] = {
    icon = "",
    color = "#cc00ff",
    cterm_color = "67",
    name = "Pyc",
  },
  ["pyd"] = {
    icon = "",
    color = "#cc00ff",
    cterm_color = "67",
    name = "Pyd",
  },
  ["pyo"] = {
    icon = "",
    color = "#cc00ff",
    cterm_color = "67",
    name = "Pyo",
  },
  ["r"] = {
    icon = "ﳒ",
    color = "#ffad49",
    cterm_color = "65",
    name = "R",
  },
  ["rake"] = {
    icon = "",
    color = "#cd1bfd",
    cterm_color = "52",
    name = "Rake",
  },
  ["rakefile"] = {
    icon = "",
    color = "#cd1bfd",
    cterm_color = "52",
    name = "Rakefile",
  },
  ["rb"] = {
    icon = "",
    color = "#cd1bfd",
    cterm_color = "52",
    name = "Rb",
  },
  ["rlib"] = {
    icon = "",
    color = "#ff8d01",
    cterm_color = "180",
    name = "Rlib",
  },
  ["rmd"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Rmd",
  },
  ["rproj"] = {
    icon = "鉶",
    color = "#ffad49",
    cterm_color = "65",
    name = "Rproj",
  },
  ["rs"] = {
    icon = "",
    color = "#ff8d01",
    cterm_color = "180",
    name = "Rs",
  },
  ["rss"] = {
    icon = "",
    color = "#FB9D3B",
    cterm_color = "215",
    name = "Rss",
  },
  ["sass"] = {
    icon = "",
    color = "#14ffa9",
    cterm_color = "204",
    name = "Sass",
  },
  ["scala"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "167",
    name = "Scala",
  },
  ["scss"] = {
    icon = "",
    color = "#14ffa9",
    cterm_color = "204",
    name = "Scss",
  },
  ["sh"] = {
    icon = "",
    color = "#b6aef4",
    cterm_color = "59",
    name = "Sh",
  },
  ["sig"] = {
    icon = "λ",
    color = "#ffad49",
    cterm_color = "173",
    name = "Sig",
  },
  ["slim"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "166",
    name = "Slim",
  },
  ["sln"] = {
    icon = "",
    color = "#854CC7",
    cterm_color = "98",
    name = "Sln",
  },
  ["sml"] = {
    icon = "λ",
    color = "#ffad49",
    cterm_color = "173",
    name = "Sml",
  },
  ["sql"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "188",
    name = "Sql",
  },
  ["sqlite"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "188",
    name = "Sql",
  },
  ["sqlite3"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "188",
    name = "Sql",
  },
  ["styl"] = {
    icon = "",
    color = "#72e9f4",
    cterm_color = "107",
    name = "Styl",
  },
  ["sublime"] = {
    icon = "",
    color = "#ffad49",
    cterm_color = "98",
    name = "Suo",
  },
  ["suo"] = {
    icon = "",
    color = "#854CC7",
    cterm_color = "98",
    name = "Suo",
  },
  ["sv"] = {
    icon = "",
    color = "#46a07b",
    cterm_color = "29",
    name = "SystemVerilog",
  },
  ["svelte"] = {
    icon = "",
    color = "#b6aef4",
    cterm_color = "202",
    name = "Svelte",
  },
  ["svh"] = {
    icon = "",
    color = "#46a07b",
    cterm_color = "29",
    name = "SystemVerilog",
  },
  ["svg"] = {
    icon = "ﰟ",
    color = "#ffad49",
    cterm_color = "215",
    name = "Svg",
  },
  ["swift"] = {
    icon = "",
    color = "#ffad49",
    cterm_color = "173",
    name = "Swift",
  },
  ["t"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Tor",
  },
  ["tbc"] = {
    icon = "﯑",
    color = "#b6aef4",
    cterm_color = "67",
    name = "Tcl",
  },
  ["tcl"] = {
    icon = "﯑",
    color = "#b6aef4",
    cterm_color = "67",
    name = "Tcl",
  },
  ["terminal"] = {
    icon = "",
    color = "#89c9ec",
    cterm_color = "71",
    name = "Terminal",
  },
  ["tex"] = {
    icon = "ﭨ",
    color = "#9d00ff",
    cterm_color = "58",
    name = "Tex",
  },
  ["toml"] = {
    icon = "",
    color = "#89c9ec",
    cterm_color = "66",
    name = "Toml",
  },
  ["tres"] = {
    icon = "",
    color = "#45f3d3",
    cterm_color = "185",
    name = "TextResource",
  },
  ["ts"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Ts",
  },
  ["tscn"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "TextScene",
  },
  ["tsx"] = {
    icon = "",
    color = "#299eec",
    cterm_color = "67",
    name = "Tsx",
  },
  ["twig"] = {
    icon = "",
    color = "#72e9f4",
    cterm_color = "107",
    name = "Twig",
  },
  ["txt"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "113",
    name = "Txt",
  },
  ["v"] = {
    icon = "",
    color = "#46a07b",
    cterm_color = "29",
    name = "Verilog",
  },
  ["vh"] = {
    icon = "",
    color = "#46a07b",
    cterm_color = "29",
    name = "Verilog",
  },
  ["vhd"] = {
    icon = "",
    color = "#46a07b",
    cterm_color = "29",
    name = "VHDL",
  },
  ["vhdl"] = {
    icon = "",
    color = "#46a07b",
    cterm_color = "29",
    name = "VHDL",
  },
  ["vim"] = {
    icon = "",
    color = "#46a07b",
    cterm_color = "29",
    name = "Vim",
  },
  ["vue"] = {
    icon = "﵂",
    color = "#72e9f4",
    cterm_color = "107",
    name = "Vue",
  },
  ["webmanifest"] = {
    icon = "",
    color = "#14ffa9",
    cterm_color = "221",
    name = "Webmanifest",
  },
  ["webp"] = {
    icon = "",
    color = "#d5bdff",
    cterm_color = "140",
    name = "Webp",
  },
  ["webpack"] = {
    icon = "ﰩ",
    color = "#299eec",
    cterm_color = "67",
    name = "Webpack",
  },
  ["xcplayground"] = {
    icon = "",
    color = "#ffad49",
    cterm_color = "173",
    name = "XcPlayground",
  },
  ["xls"] = {
    icon = "",
    color = "#46a07b",
    cterm_color = "23",
    name = "Xls",
  },
  ["xml"] = {
    icon = "謹",
    color = "#ffad49",
    cterm_color = "173",
    name = "Xml",
  },
  ["xul"] = {
    icon = "",
    color = "#ffad49",
    cterm_color = "173",
    name = "Xul",
  },
  ["yaml"] = {
    icon = "",
    color = "#89c9ec",
    cterm_color = "66",
    name = "Yaml",
  },
  ["yml"] = {
    icon = "",
    color = "#89c9ec",
    cterm_color = "66",
    name = "Yml",
  },
  ["zig"] = {
    icon = "",
    color = "#f69a1b",
    cterm_color = "208",
    name = "Zig",
  },
  ["zsh"] = {
    icon = "",
    color = "#7700ff",
    cterm_color = "113",
    name = "Zsh",
  },
  ["sol"] = {
    icon = "ﲹ",
    color = "#299eec",
    cterm_color = "67",
    name = "Solidity",
  },
  [".env"] = {
    icon = "",
    color = "#cb1dfd",
    cterm_color = "226",
    name = "Env",
  },
  ["prisma"] = {
    icon = "卑",
    color = "#ffffff",
    cterm_color = "white",
    name = "Prisma",
  },
  ["lock"] = {
    icon = "",
    color = "#bbbbbb",
    cterm_color = "250",
    name = "Lock",
  },
  ["log"] = {
    icon = "",
    color = "#ffffff",
    cterm_color = "white",
    name = "Log",
  }
  }
